version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: pods
        MYSQL_DATABASE: pods
        MYSQL_USER: pods
        MYSQL_PASSWORD: pods
  www:
    image: drupal:9-php7.4-apache
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -ex

        # Install Git (required by Composer).
        apt-get update && apt-get install -y git

        # Build PODS via Composer, if necessary.
        if [ ! -d /opt/drupal/vendor ]; then
          composer install
        fi

        # Run Apache.
        apache2-foreground

    depends_on:
      - db
    volumes:
      - './:/opt/drupal'
    ports:
      - '85:80'
