version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: farm
        MYSQL_DATABASE: farm
        MYSQL_USER: farm
        MYSQL_PASSWORD: farm
  www:
    depends_on:
      - db
    volumes:
      - './web/modules/custom:/opt/drupal/PODS/web/modules/custom'
      - './logs:/var/log/apache2/'
    image: pods:latest
    ports:
      - '85:80'
