version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: pods
        MYSQL_DATABASE: pods
        MYSQL_USER: pods
        MYSQL_PASSWORD: pods
  www:
    image: drupal:9-php7.4-apache
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -ex

        # Install Git (required by Composer).
        apt-get update && apt-get install -y git

        # If the vendor directory doesn't exist, assume a fresh install.
        if [ ! -d /opt/drupal/vendor ]; then

          # Build the PODS codebase via Composer.
          composer install

          # Install Drupal via Drush.
          drush site-install -y --existing-config --db-url=mysql://farm:farm@db/farm --account-pass=admin farm farm.modules="base"

          # Make sites/default/files writable by Apache.
          chown -R root:www-data /opt/drupal/web/sites/default/files

          # Import taxonomy terms via Drush.
          drush -y import:taxonomies --choice=full

          # Enable USDA eAuth testing module via Drush.
          drush en -y usda_eauth_test

          # Add a test user.
          drush user:create test --mail="test@example.com" --password="test"
        fi

        # Notify that PODS is ready.
        echo "##### PODS IS READY #####"

        # Run Apache.
        apache2-foreground

    depends_on:
      - db
    volumes:
      - './:/opt/drupal'
    ports:
      - '85:80'
