version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
            - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: farm
        MYSQL_DATABASE: farm
        MYSQL_USER: farm
        MYSQL_PASSWORD: farm

  pods-container:
    depends_on:
      - db
    volumes:
      - './web/modules/custom:/opt/drupal/PODS/web/modules/custom'
      - './logs:/var/log/apache2/'
    image: pods:latest
    ports:
      - '85:80'
    # environment:
      # XDEBUG_MODE: debug
      # XDEBUG_CONFIG: client_host=172.17.0.1
      # Enable these for PHPStorm:
      #XDEBUG_SESSION: PHPSTORM
      #PHP_IDE_CONFIG: serverName=localhost

  # Enable this service when executing javascript tests.
#  chrome:
#    image: selenium/standalone-chrome:latest
